name: 'get-version-action'
description: 'Get version string from your project file'
author: 'bbonkr'
branding:
  color: purple 
  icon: check
inputs:
  project: 
    required: true
    description: 'Project file path'
outputs:
  version:
    description: 'Found version'
  major:
    description: 'Major of SEMVER'
  minor:
    description: 'Minor of SEMVER'
  patch:
    description: 'Patch of SEMVER'
  pre-release:
    description: 'Pre-release of SEMVER'
  build:
    description: 'Build of SEMVER'
runs:
  using: 'node20'
  main: 'dist/index.js'
