name: 'Verify PR'

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: |
          npm install

      - name: Run all npm script
        run: |
          npm run all

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - uses: ./
        id: get_version
        with:
          project: ./package.json
          show_log_message: false

      - name: log
        run: |
          echo "version:      ${{ steps.get_version.outputs.version }}"
          echo "major:        ${{ steps.get_version.outputs.major }}"
          echo "minor:        ${{ steps.get_version.outputs.minor }}"
          echo "patch:        ${{ steps.get_version.outputs.patch }}"
          echo "pre-release:  ${{ steps.get_version.outputs.pre-release }}"
          echo "build:        ${{ steps.get_version.outputs.build }}"
